name = "oculus-food-tracker"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
dist = "dist"
pages_build_output_dir = "dist"

[site]
bucket = "./dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[[routes]]
pattern = "/api/*"
script = "/functions/api/[segment]"
